name: Check new releases

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_release
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            // Load release list from GitHub
            let releaseList = await github.rest.repos.listReleases({
                repo: context.repo.repo,
                owner: context.repo.owner,
                per_page: 100,
                page: 1
            });

            for (let i = 0; i < releaseList.data.length; i++) {
                let releaseListElement = releaseList.data[i];

                console.log(`Release: ${releaseListElement}`);

                if (!releaseListElement.draft && !releaseListElement.prerelease) {
                    console.log(`Chosen: ${releaseListElement.id}`);
                    core.setOutput('name', releaseListElement.name);
                    break;
                }
            }

      - name: My last release
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 10

      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"

      - name: Check LLVM versions
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            let latest_version='${{ steps.last_release.outputs.name }}'.trim();
            if (latest_version === '') {
              latest_version = '18.1.0';
            }

            // Function to compare two version strings
            function compareVersions(a, b) {
              const partsA = a.split('.');
              const partsB = b.split('.');
              const maxLength = Math.max(partsA.length, partsB.length);

              for (let i = 0; i < maxLength; i++) {
                const numA = parseInt(partsA[i]) || 0;
                const numB = parseInt(partsB[i]) || 0;
                if (numA !== numB) {
                  return numA - numB;
                }
              }
              return 0;
            }

            let versions_to_trigger = [];

            let output = "";

            const options = {};
            options.listeners = {
              stdout: (data) => {
                output += data.toString();
              },
              stderr: (data) => {
                console.error(`stderr: ${data.toString()}`);
              }
            };

            await exec.exec('git', ['ls-remote', '--tags', '--refs', '--sort=-version:refname', 'https://github.com/llvm/llvm-project', 'llvmorg-*'], options);

            // Split the output into an array of lines
            const lines = output.split('\n');
          
            for(const line of lines) {
              // Split the line into oid and ref
              const [oid, ref] = line.split('\t');

              if (!oid || !ref) {
                continue;
              }

              // Remove prefix from ref
              const version = ref.replace('refs/tags/llvmorg-', '');
          
              // Check if version consists only of numbers and dots
              if (/^[0-9.]+$/.test(version)) {
                // Compare versions
                if (compareVersions(version, latest_version) > 0) {
                  console.log(`${version} is greater, need to build binaries`);

                  versions_to_trigger.push(version)
                } else {
                  console.log(`${version} is smaller than our release. No need to trigger build`);
                }
              }
            }

            for(const version of versions_to_trigger) {
              console.log(`Triggering build action for version: ${version}`);

              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'build_binaries.yaml',
                version_to_build: version
              });
            }


        